[package]
name = "mlx"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mlx-sys = { path = "../mlx-sys" }
mlx-derive = {path = "../mlx-derive"}


[[example]]
name = "basic_ops"

[[example]]
name = "mlp"

